## Basic Configuration
title: "0xReki's Adventures by Night"
description: "Creative Writing, Mahjong and more!"

source: docs-src
destination: docs

url: https://0xreki.github.io/crystaldown
static_url: https://0xreki.github.io
breadcrumb_domain: https://0xreki.github.io

permalink: pretty
future: true

### Copyright
copyright:
  license: <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>
  name: Thai “0xReki” Chung
  url: https://0xreki.de/about-me/

# Comments
comments:
  action: /thanks-for-commenting/

### SASS
sass:
  style: compressed
  cache: false

### Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-last-modified-at
  - jekyll-include-cache
  - jekyll-wns

remote_theme: 0xReki/crystaldown-theme

patreon:
  title: Become a Patron to get early access to new chapters
  url: https://www.patreon.com/RWNS

# Optimizations
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]

preload:
  fonts:
  - /assets/fonts/Cardo-Regular.woff2
  - /assets/fonts/Cardo-Bold.woff2
  - /assets/fonts/Source-Sans-Pro-Regular.woff2
  - /assets/fonts/Source-Sans-Pro-Bold.woff2

liquid:
  error_mode: warn

# Syntax
markdown: kramdown

wns:
  quads: true
  abbreviations: true

## Defaults
defaults:
  - # /
    scope:
      path: ""
    values:
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.png
      published: true
      image: /assets/images/site-og.png
      canonical_domain: https://0xreki.de/scions
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /_posts
    scope:
      path: "_posts"
    values:
      category: scions
      layout: 2020/post
      type: post
      lang: "en-CA"
      author: reki
      publisher: reki
      image: /assets/images/site-og.png
      comments: true
      commenting: open
      published: true
      image: /assets/images/site-og.png
      permalink: /:year/:month-:day-:title/
      canonical_domain: https://0xreki.de/scions
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/
  - # /01-children-of-light-and-darkness
    scope:
      path: "/01-children-of-light-and-darkness"
    values:
      layout: 2020/chapter
      type: chapter
      lang: "en-CA"
      author: reki
      publisher: reki
      published: true
      termbase: /crystaldown
      book:
        number: 1
        series: "Crystal Down: Scions"
        copyrightYear: 2020
        title: "Children of Light and Darkness"
        url: "/scions/#volume-01-children-of-light-and-darkness"
        genres:
          - Adventure
          - Fantasy
          - LitRPG
          - Slice of Life
      image: /assets/images/site-og.png
      canonical_domain: https://0xreki.de/scions
      intermediate_breadcrumbs:
        -
          title: Archived Projects
          url: /archive/